# repository locaton settings
# path to keepass file with sensible information
# github settings
# zshrc local
# zimrc local
# warppoints
# brew packages
# cask packages
# apple store packages
# vscode gist for extensions
# mendeley dir
# macos dock files 